---
title: "About this site"
description: |
  Some additional details about the website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Why this site

1. A easy, fun, and informative way to share my research identity and academic notes

2. A way to reflect - on the practical side of my research, in particular

3. A way to interact - with researchers, educators, and all

4. Potential contributions to the educational research field in my home country


## Notes for building a distill website

Disclaimer: this is NOT a tutorial and don't use this if any of the following doesn't make sense to you.

Things are not easy if you want use version control on a distill website. Many ways to do it but no easy ways. After multiple attempts, I figured out these steps working for my purpose:

1. Create a new repo on GitHub, don't initiate anything, an empty repo will do (remember to copy the URL)

2. In RStudio IDE, create a new project, select distill blog/website (remember to check the configuration with github page), distill will create basic things you need for the web

3. How to push your local project to the existing repo? Well, use your terminal.

git init  
git add .  
git commit -m 'First commit'  
git remote add origin PUT THE URL HERE  
git remote -v  
git push origin master  

4. Go to your GitHub repo to confirm whether the files are there. 

5. Go back to your RStudio IDE, under the tools-version control-set up while noticing the URL is automatically copied there. Click Ok. Restart your RStudio IDE. Git is available now.

6. You think the Git function is working and you're all good. No you are not. The pull and push buttons do not work.

git push -u origin master  

YOU ARE NOW ALL SET.


